### ISSUE TITLE
epoch [59] | lr [0.0010000000] | batch_idx [170] | loc_loss [0.741] | cls_loss [1.775] | total_loss [430.194] | [0min,29sec] Traceback (most recent call last):   File "train.py", line 162, in <module>     scheduler.step() NameError: name 'scheduler' is not defined

### ISSUE THREAD

**Issue by angyee** [modernkim/ResNet_SSD_Pytorch#1]
epoch [59] | lr [0.0010000000] | batch_idx [170] | loc_loss [0.741] | cls_loss [1.775] | total_loss [430.194] | [0min,29sec]
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    scheduler.step()
NameError: name 'scheduler' is not defined

**Comment by DaehanKim-Korea** [comment]
Oh thank you for leaving the issue.
Perhaps,

[config.py 17line]

Did you check it? lr_scheduler = True

Did you do print(opt.lr_scheduler)?

**Comment by angyee** [comment]
yes 
lr_scheduler = True
print(opt.lr_scheduler) - not tested

**Comment by DaehanKim-Korea** [comment]
Not when I implemented it. If there is a problem, you can define and use it.
