### ISSUE TITLE
Why is 1 being subtracted here?

### ISSUE THREAD

**Issue by sparsh-b** [modernkim/ResNet_SSD_Pytorch#3]
https://github.com/koreadhkim/ResNet_SSD_Pytorch/blob/9a034bd3e6a5db01f2ce1a104edd5d4ce990ef9a/data/voc_train_data_loader.py#L94

**Comment by DaehanKim-Korea** [comment]
Did you solve it? The simplest way is to turn on the Jupiter Notebook. It's about bringing in the data and visualizing it.
