### ISSUE TITLE
Request for clarity regarding `VOC_LABELS` & `num_classes`

### ISSUE THREAD

**Issue by sparsh-b** [modernkim/ResNet_SSD_Pytorch#4]
Hi @koreadhkim ,

`num_classes` is set to 21 at: https://github.com/koreadhkim/ResNet_SSD_Pytorch/blob/9a034bd3e6a5db01f2ce1a104edd5d4ce990ef9a/config.py#L9

But VOC_LABELS at: https://github.com/koreadhkim/ResNet_SSD_Pytorch/blob/9a034bd3e6a5db01f2ce1a104edd5d4ce990ef9a/data/voc_train_data_loader.py#L13
has only names of 20 classes

Can I please know the reason behind this..

**Comment by DaehanKim-Korea** [comment]
One additional class in the background.

**Comment by sparsh-b** [comment]
Can you please point me to the code where index 0 is being assigned for background class..

Thanks!
